# Elasticsearch default vars
elastic_search_url_base: "https://artifacts.elastic.co/downloads/elasticsearch"
elastic_search_version: "elasticsearch-7.17.28-amd64.deb"
checksum_url: "{{ elastic_search_url_base }}/{{ elastic_search_version }}.sha512"
elasticsearch_config: "elasticsearch.yml.j2"

# Demo_int specific version
elastic_search_version_demo_int: "elasticsearch-8.19.7-amd64.deb"
elasticsearch_config_demo_int: "elasticsearch-demo-int.yml.j2"

es_url: "http://localhost:9200"

# Toggle rolling upgrade orchestration
rolling_upgrade: false
bootstrap: "{{ not (rolling_upgrade | bool)}}"

# Elasticsearch data path
es_data_path: "/datadisks/disk1/elasticsearch/data"

# Custom JVM options
jvm_custom_options: |
  -Xms8g
  -Xmx8g

# Systemd service override content
service_override: |
  [Service]
  LimitMEMLOCK=infinity